POST http://localhost:8000/user/login HTTP/1.1
Content-Type: application/json 

{
    "username": "hu",
    "password": "pwd"
}

### 
GET http://localhost:8000/game/start/hu

###
GET http://localhost:8000/game/draw-card/hu HTTP/1.1


###
GET http://localhost:8000/game/leader-board


###
GET https://gocats.onrender.com/game/start/h